
package com.onnorokomsms.api;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SendSms", targetNamespace = "http://api.onnorokomsms.com/", wsdlLocation = "file:/C:/Users/cyclingbd007/Desktop/OnnorokomWSDL.wsdl")
public class SendSms extends Service {

	private final static URL SENDSMS_WSDL_LOCATION;
	private final static WebServiceException SENDSMS_EXCEPTION;
	private final static QName SENDSMS_QNAME = new QName("http://api.onnorokomsms.com/", "SendSms");

	static {
		URL url = null;
		WebServiceException e = null;
		try {
			url = new URL("https://api2.onnorokomsms.com/sendsms.asmx?WSDL");
		} catch (MalformedURLException ex) {
			e = new WebServiceException(ex);
		}
		SENDSMS_WSDL_LOCATION = url;
		SENDSMS_EXCEPTION = e;
	}

	public SendSms() {
		super(__getWsdlLocation(), SENDSMS_QNAME);
	}

	public SendSms(WebServiceFeature... features) {
		super(__getWsdlLocation(), SENDSMS_QNAME, features);
	}

	public SendSms(URL wsdlLocation) {
		super(wsdlLocation, SENDSMS_QNAME);
	}

	public SendSms(URL wsdlLocation, WebServiceFeature... features) {
		super(wsdlLocation, SENDSMS_QNAME, features);
	}

	public SendSms(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public SendSms(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
		super(wsdlLocation, serviceName, features);
	}

	/**
	 * 
	 * @return returns SendSmsSoap
	 */
	@WebEndpoint(name = "SendSmsSoap")
	public SendSmsSoap getSendSmsSoap() {
		return super.getPort(new QName("http://api.onnorokomsms.com/", "SendSmsSoap"), SendSmsSoap.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure on
	 *            the proxy. Supported features not in the <code>features</code>
	 *            parameter will have their default values.
	 * @return returns SendSmsSoap
	 */
	@WebEndpoint(name = "SendSmsSoap")
	public SendSmsSoap getSendSmsSoap(WebServiceFeature... features) {
		return super.getPort(new QName("http://api.onnorokomsms.com/", "SendSmsSoap"), SendSmsSoap.class, features);
	}

	private static URL __getWsdlLocation() {
		if (SENDSMS_EXCEPTION != null) {
			throw SENDSMS_EXCEPTION;
		}
		return SENDSMS_WSDL_LOCATION;
	}

}
