
package com.onnorokomsms.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SendSmsSoap", targetNamespace = "http://api.onnorokomsms.com/")
@XmlSeeAlso({ ObjectFactory.class })
public interface SendSmsSoap {

	/**
	 * 
	 * @param messageHeader
	 * @param wsSmses
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "OneToOneBulk", action = "http://api.onnorokomsms.com/OneToOneBulk")
	@WebResult(name = "OneToOneBulkResult", targetNamespace = "http://api.onnorokomsms.com/")
	@RequestWrapper(localName = "OneToOneBulk", targetNamespace = "http://api.onnorokomsms.com/", className = "com.onnorokomsms.api.OneToOneBulk")
	@ResponseWrapper(localName = "OneToOneBulkResponse", targetNamespace = "http://api.onnorokomsms.com/", className = "com.onnorokomsms.api.OneToOneBulkResponse")
	public String oneToOneBulk(
			@WebParam(name = "messageHeader", targetNamespace = "http://api.onnorokomsms.com/") MessageHeader messageHeader,
			@WebParam(name = "wsSmses", targetNamespace = "http://api.onnorokomsms.com/") ArrayOfWsSms wsSmses);

	/**
	 * 
	 * @param userPassword
	 * @param maskName
	 * @param mobileNumber
	 * @param userName
	 * @param type
	 * @param campaignName
	 * @param smsText
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "OneToOne", action = "http://api.onnorokomsms.com/OneToOne")
	@WebResult(name = "OneToOneResult", targetNamespace = "http://api.onnorokomsms.com/")
	@RequestWrapper(localName = "OneToOne", targetNamespace = "http://api.onnorokomsms.com/", className = "com.onnorokomsms.api.OneToOne")
	@ResponseWrapper(localName = "OneToOneResponse", targetNamespace = "http://api.onnorokomsms.com/", className = "com.onnorokomsms.api.OneToOneResponse")
	public String oneToOne(
			@WebParam(name = "userName", targetNamespace = "http://api.onnorokomsms.com/") String userName,
			@WebParam(name = "userPassword", targetNamespace = "http://api.onnorokomsms.com/") String userPassword,
			@WebParam(name = "mobileNumber", targetNamespace = "http://api.onnorokomsms.com/") String mobileNumber,
			@WebParam(name = "smsText", targetNamespace = "http://api.onnorokomsms.com/") String smsText,
			@WebParam(name = "type", targetNamespace = "http://api.onnorokomsms.com/") String type,
			@WebParam(name = "maskName", targetNamespace = "http://api.onnorokomsms.com/") String maskName,
			@WebParam(name = "campaignName", targetNamespace = "http://api.onnorokomsms.com/") String campaignName);

	/**
	 * 
	 * @param messageText
	 * @param userPassword
	 * @param maskName
	 * @param smsType
	 * @param numberList
	 * @param userName
	 * @param campaignName
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "OneToMany", action = "http://api.onnorokomsms.com/OneToMany")
	@WebResult(name = "OneToManyResult", targetNamespace = "http://api.onnorokomsms.com/")
	@RequestWrapper(localName = "OneToMany", targetNamespace = "http://api.onnorokomsms.com/", className = "com.onnorokomsms.api.OneToMany")
	@ResponseWrapper(localName = "OneToManyResponse", targetNamespace = "http://api.onnorokomsms.com/", className = "com.onnorokomsms.api.OneToManyResponse")
	public String oneToMany(
			@WebParam(name = "userName", targetNamespace = "http://api.onnorokomsms.com/") String userName,
			@WebParam(name = "userPassword", targetNamespace = "http://api.onnorokomsms.com/") String userPassword,
			@WebParam(name = "messageText", targetNamespace = "http://api.onnorokomsms.com/") String messageText,
			@WebParam(name = "numberList", targetNamespace = "http://api.onnorokomsms.com/") String numberList,
			@WebParam(name = "smsType", targetNamespace = "http://api.onnorokomsms.com/") String smsType,
			@WebParam(name = "maskName", targetNamespace = "http://api.onnorokomsms.com/") String maskName,
			@WebParam(name = "campaignName", targetNamespace = "http://api.onnorokomsms.com/") String campaignName);

	/**
	 * 
	 * @param userPassword
	 * @param userName
	 * @param responseId
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "DeliveryStatus", action = "http://api.onnorokomsms.com/DeliveryStatus")
	@WebResult(name = "DeliveryStatusResult", targetNamespace = "http://api.onnorokomsms.com/")
	@RequestWrapper(localName = "DeliveryStatus", targetNamespace = "http://api.onnorokomsms.com/", className = "com.onnorokomsms.api.DeliveryStatus")
	@ResponseWrapper(localName = "DeliveryStatusResponse", targetNamespace = "http://api.onnorokomsms.com/", className = "com.onnorokomsms.api.DeliveryStatusResponse")
	public String deliveryStatus(
			@WebParam(name = "userName", targetNamespace = "http://api.onnorokomsms.com/") String userName,
			@WebParam(name = "userPassword", targetNamespace = "http://api.onnorokomsms.com/") String userPassword,
			@WebParam(name = "responseId", targetNamespace = "http://api.onnorokomsms.com/") String responseId);

	/**
	 * 
	 * @param userPassword
	 * @param userName
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetBalance", action = "http://api.onnorokomsms.com/GetBalance")
	@WebResult(name = "GetBalanceResult", targetNamespace = "http://api.onnorokomsms.com/")
	@RequestWrapper(localName = "GetBalance", targetNamespace = "http://api.onnorokomsms.com/", className = "com.onnorokomsms.api.GetBalance")
	@ResponseWrapper(localName = "GetBalanceResponse", targetNamespace = "http://api.onnorokomsms.com/", className = "com.onnorokomsms.api.GetBalanceResponse")
	public String getBalance(
			@WebParam(name = "userName", targetNamespace = "http://api.onnorokomsms.com/") String userName,
			@WebParam(name = "userPassword", targetNamespace = "http://api.onnorokomsms.com/") String userPassword);

	/**
	 * 
	 * @param userPassword
	 * @param userName
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetMask", action = "http://api.onnorokomsms.com/GetMask")
	@WebResult(name = "GetMaskResult", targetNamespace = "http://api.onnorokomsms.com/")
	@RequestWrapper(localName = "GetMask", targetNamespace = "http://api.onnorokomsms.com/", className = "com.onnorokomsms.api.GetMask")
	@ResponseWrapper(localName = "GetMaskResponse", targetNamespace = "http://api.onnorokomsms.com/", className = "com.onnorokomsms.api.GetMaskResponse")
	public String getMask(
			@WebParam(name = "userName", targetNamespace = "http://api.onnorokomsms.com/") String userName,
			@WebParam(name = "userPassword", targetNamespace = "http://api.onnorokomsms.com/") String userPassword);

	/**
	 * 
	 * @param messageText
	 * @param apiKey
	 * @param maskName
	 * @param smsType
	 * @param numberList
	 * @param campaignName
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "NumberSms", action = "http://api.onnorokomsms.com/NumberSms")
	@WebResult(name = "NumberSmsResult", targetNamespace = "http://api.onnorokomsms.com/")
	@RequestWrapper(localName = "NumberSms", targetNamespace = "http://api.onnorokomsms.com/", className = "com.onnorokomsms.api.NumberSms")
	@ResponseWrapper(localName = "NumberSmsResponse", targetNamespace = "http://api.onnorokomsms.com/", className = "com.onnorokomsms.api.NumberSmsResponse")
	public String numberSms(@WebParam(name = "apiKey", targetNamespace = "http://api.onnorokomsms.com/") String apiKey,
			@WebParam(name = "messageText", targetNamespace = "http://api.onnorokomsms.com/") String messageText,
			@WebParam(name = "numberList", targetNamespace = "http://api.onnorokomsms.com/") String numberList,
			@WebParam(name = "smsType", targetNamespace = "http://api.onnorokomsms.com/") String smsType,
			@WebParam(name = "maskName", targetNamespace = "http://api.onnorokomsms.com/") String maskName,
			@WebParam(name = "campaignName", targetNamespace = "http://api.onnorokomsms.com/") String campaignName);

	/**
	 * 
	 * @param apiKey
	 * @param maskName
	 * @param wsSmses
	 * @param campaignName
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "ListSms", action = "http://api.onnorokomsms.com/ListSms")
	@WebResult(name = "ListSmsResult", targetNamespace = "http://api.onnorokomsms.com/")
	@RequestWrapper(localName = "ListSms", targetNamespace = "http://api.onnorokomsms.com/", className = "com.onnorokomsms.api.ListSms")
	@ResponseWrapper(localName = "ListSmsResponse", targetNamespace = "http://api.onnorokomsms.com/", className = "com.onnorokomsms.api.ListSmsResponse")
	public String listSms(@WebParam(name = "apiKey", targetNamespace = "http://api.onnorokomsms.com/") String apiKey,
			@WebParam(name = "wsSmses", targetNamespace = "http://api.onnorokomsms.com/") ArrayOfWsSms wsSmses,
			@WebParam(name = "maskName", targetNamespace = "http://api.onnorokomsms.com/") String maskName,
			@WebParam(name = "campaignName", targetNamespace = "http://api.onnorokomsms.com/") String campaignName);

	/**
	 * 
	 * @param apiKey
	 * @param responseId
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "SMSDeliveryStatus", action = "http://api.onnorokomsms.com/SMSDeliveryStatus")
	@WebResult(name = "SMSDeliveryStatusResult", targetNamespace = "http://api.onnorokomsms.com/")
	@RequestWrapper(localName = "SMSDeliveryStatus", targetNamespace = "http://api.onnorokomsms.com/", className = "com.onnorokomsms.api.SMSDeliveryStatus")
	@ResponseWrapper(localName = "SMSDeliveryStatusResponse", targetNamespace = "http://api.onnorokomsms.com/", className = "com.onnorokomsms.api.SMSDeliveryStatusResponse")
	public String smsDeliveryStatus(
			@WebParam(name = "apiKey", targetNamespace = "http://api.onnorokomsms.com/") String apiKey,
			@WebParam(name = "responseId", targetNamespace = "http://api.onnorokomsms.com/") String responseId);

	/**
	 * 
	 * @param apiKey
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetCurrentBalance", action = "http://api.onnorokomsms.com/GetCurrentBalance")
	@WebResult(name = "GetCurrentBalanceResult", targetNamespace = "http://api.onnorokomsms.com/")
	@RequestWrapper(localName = "GetCurrentBalance", targetNamespace = "http://api.onnorokomsms.com/", className = "com.onnorokomsms.api.GetCurrentBalance")
	@ResponseWrapper(localName = "GetCurrentBalanceResponse", targetNamespace = "http://api.onnorokomsms.com/", className = "com.onnorokomsms.api.GetCurrentBalanceResponse")
	public String getCurrentBalance(
			@WebParam(name = "apiKey", targetNamespace = "http://api.onnorokomsms.com/") String apiKey);

	/**
	 * 
	 * @param apiKey
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetAllMask", action = "http://api.onnorokomsms.com/GetAllMask")
	@WebResult(name = "GetAllMaskResult", targetNamespace = "http://api.onnorokomsms.com/")
	@RequestWrapper(localName = "GetAllMask", targetNamespace = "http://api.onnorokomsms.com/", className = "com.onnorokomsms.api.GetAllMask")
	@ResponseWrapper(localName = "GetAllMaskResponse", targetNamespace = "http://api.onnorokomsms.com/", className = "com.onnorokomsms.api.GetAllMaskResponse")
	public String getAllMask(
			@WebParam(name = "apiKey", targetNamespace = "http://api.onnorokomsms.com/") String apiKey);

}
